import os
import shutil
import subprocess
import requests
import glob
from pyrogram import Client, filters

# Mengambil konfigurasi dari GitHub Secrets
API_ID = int(os.environ.get("API_ID"))
API_HASH = os.environ.get("API_HASH")
SESSION_STRING = os.environ.get("SESSION_STRING")
GITHUB_USERNAME = os.environ.get("GH_USERNAME")
GITHUB_TOKEN = os.environ.get("GH_TOKEN")

# Inisialisasi Userbot menggunakan Session String
app = Client(
    "twrp_userbot",
    session_string=SESSION_STRING,
    api_id=API_ID,
    api_hash=API_HASH
)

@app.on_message(filters.command("start", prefixes=["/", "."]) & filters.private)
async def start(client, message):
    teks = (
        "🤖 **Generator Device Tree TWRP (Userbot Mode AKTIF)**\n\n"
        "Batas ukuran Telegram API telah ditembus. Sekarang mendukung file hingga 2 GB!\n\n"
        "**Cara Penggunaan:**\n"
        "Kirimkan file berekstensi `.img` dan **wajib** ketik `/dt` pada kolom keterangan (caption) dokumen."
    )
    await message.reply_text(teks)

# Filter hanya merespons dokumen berekstensi .img dengan caption /dt
@app.on_message(filters.document & filters.private)
async def handle_document(client, message):
    if not message.caption or message.caption.strip().lower() != "/dt":
        return
        
    if not message.document.file_name.endswith('.img'):
        await message.reply_text("❌ Harap kirimkan file dengan ekstensi `.img`!")
        return

    msg = await message.reply_text("⏳ Mengunduh file `.img` Anda... \n*(Kecepatan turbo aktif berkat Userbot + tgcrypto)*")

    try:
        work_dir = "workspace"
        os.makedirs(work_dir, exist_ok=True)
        
        # Proses unduh file raksasa
        file_path = await client.download_media(message, file_name=f"{work_dir}/boot.img")

        await msg.edit_text("⚙️ Mengekstrak Device Tree dengan twrpdtgen...")

        output_dir = os.path.join(work_dir, "output")
        if os.path.exists(output_dir):
            shutil.rmtree(output_dir)

        # Proses Ekstrak
        result = subprocess.run(["python3", "-m", "twrpdtgen", file_path, "-o", output_dir], capture_output=True, text=True)
        
        if result.returncode != 0:
            await msg.edit_text(f"❌ Gagal mengekstrak device tree.\n\nLog:\n`{result.stderr}`")
            return

        # Membaca struktur folder output
        manufacturers = os.listdir(output_dir)
        if not manufacturers:
            raise Exception("Folder output kosong.")
        manufacturer = manufacturers[0]
        
        codenames = os.listdir(os.path.join(output_dir, manufacturer))
        if not codenames:
            raise Exception("Tidak dapat menemukan codename perangkat.")
        codename = codenames[0]

        device_tree_path = os.path.join(output_dir, manufacturer, codename)
        repo_name = f"android_device_{manufacturer}_{codename}"
        
        await msg.edit_text(f"✅ Ekstraksi berhasil!\n🚀 Membuat repositori dan mengunggah ke GitHub @{GITHUB_USERNAME}...")

        # Membuat repo GitHub via API
        headers = {
            "Authorization": f"token {GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json"
        }
        repo_data = {
            "name": repo_name,
            "description": f"TWRP Device Tree for {codename} (Auto-generated by Userbot)",
            "private": False
        }
        
        req = requests.post("https://api.github.com/user/repos", json=repo_data, headers=headers)
        if req.status_code not in [201, 422]:
            raise Exception(f"Gagal membuat repositori GitHub: {req.text}")

        # Git push proses
        subprocess.run(["git", "config", "--global", "user.email", "userbot@twrpdtgen.local"])
        subprocess.run(["git", "config", "--global", "user.name", "TWRP Userbot"])
        
        os.chdir(device_tree_path)
        subprocess.run(["git", "init"])
        subprocess.run(["git", "add", "."])
        subprocess.run(["git", "commit", "-m", "Initial commit: auto generated via Telegram Userbot"])
        subprocess.run(["git", "branch", "-M", "main"])
        
        remote_url = f"https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{repo_name}.git"
        subprocess.run(["git", "remote", "add", "origin", remote_url])
        subprocess.run(["git", "push", "-u", "origin", "main", "--force"])
        
        os.chdir("../../..")

        # Mencari Build Description dari file .mk
        build_desc = "Unknown"
        mk_files = glob.glob(f"{device_tree_path}/*.mk")
        for mk in mk_files:
            with open(mk, 'r') as f:
                content = f.read()
                if "PRIVATE_BUILD_DESC=" in content:
                    for line in content.split('\n'):
                        if "PRIVATE_BUILD_DESC=" in line:
                            build_desc = line.split('=')[1].replace('"', '').strip()
                            break

        github_link = f"https://github.com/{GITHUB_USERNAME}/{repo_name}/tree/main"
        
        final_text = (
            "✅ **TWRP device tree generated!**\n\n"
            f"📱 **Codename:** `{codename}`\n"
            f"🏭 **Manufacturer:** `{manufacturer}`\n"
            f"📋 **Build desc:** `{build_desc}`\n\n"
            f"🔗 **Device tree:** {github_link}"
        )
        
        await msg.edit_text(final_text, disable_web_page_preview=True)
        shutil.rmtree(work_dir)

    except Exception as e:
        await msg.edit_text(f"❌ Terjadi kesalahan:\n`{str(e)}`")
        if os.path.exists(work_dir):
            shutil.rmtree(work_dir)

if __name__ == "__main__":
    print("Userbot menyala dan siap menerima file .img!")
    app.run()
