name: Newsync Autobuild Dual-Client

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

concurrency:
  group: telegram-dual-bot
  cancel-in-progress: true 

jobs:
  run-bot:
    name: Running Dual-Client Bot
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cpio lz4 git

      - name: Install Python Requirements
        run: pip install pyrogram tgcrypto twrpdtgen aospdtgen requests

      - name: Start Telegram Dual-Client Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          BP_TOKEN: ${{ secrets.BP_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python newsync_autobuild.py
